    const yearSpan=document.getElementById("currentyear"),lastModifiedSpan=document.getElementById("lastModified"),currentYear=new Date().getFullYear();yearSpan.textContent=currentYear;const now=new Date,formattedDateTime=now.toLocaleString("en-US",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"});document.addEventListener("DOMContentLoaded",function(){let e=document.getElementById("menu-button"),n=document.getElementById("header-nav");e.addEventListener("click",function(){n.classList.toggle("open"),e.classList.toggle("open")})});var recipes=[{name:"Wild Rice Chicken Casserole",description:"A creamy chicken and wild rice casserole with a crispy layer of ritz crackers on top.",image:"images/chicken_casserole.webp",typeof:"dinner",ingredients:["chicken","wild rice","cream of mushroom soup","ritz crackers"]},{name:"Snickerdoodle Cookies",description:"Soft and chewy cookies with a cinnamon-sugar coating.",image:"images/snickerdoodles.webp",typeof:"dessert",ingredients:["flour","sugar","butter","cinnamon"]},{name:"Thai Peanut Chicken",description:"A spicy and savory chicken dish served over rice.",image:"images/thai_peanut_chicken.webp",typeof:"dinner",ingredients:["chicken","peanut butter","soy sauce","sriracha"]},{name:"Oatmeal Fudge Bars",description:"A layer of oatmeal cookie topped with a layer of chocolate fudge with a sprinkle of more oatmeal on top.",image:"images/fudge_bars.webp",typeof:"dessert",ingredients:["oatmeal","chocolate chips","sweetened condensed milk","butter"]},{name:"No bake cookies",description:"A chocolate and peanut butter cookie that doesn't require baking.",image:"images/no_bake_cookies.webp",typeof:"dessert",ingredients:["oatmeal","sugar","cocoa powder","peanut butter"]},{name:"French Toast",description:"A classic breakfast dish made with bread, eggs, milk, and cinnamon.",image:"images/french_toast.webp",typeof:"breakfast",ingredients:["bread","eggs","milk","cinnamon"]},{name:"German Pancakes",description:"A puffy pancake that is baked in the oven and served with powdered sugar and syrup.",image:"images/german_pancakes.webp",typeof:"breakfast",ingredients:["eggs","flour","milk","butter"]}];function getRandomRecipe(){return recipes[Math.floor(Math.random()*recipes.length)]}function updateRandomRecipe(){var e=getRandomRecipe();document.getElementById("recipe-name").textContent=e.name,document.getElementById("recipe-desc").textContent=e.description,document.querySelector("#random-recipe img").src=e.image}document.addEventListener("DOMContentLoaded",function(){var e=document.getElementById("recipe-container");console.log(e);for(var n=0;n<recipes.length;n++){console.log(recipes[n]);var t=n>=2?'loading="lazy"':"",i=document.createElement("div");i.classList.add("recipe");var a=`
                    <img src="${recipes[n].image}" alt="${recipes[n].name}" width="300" height="300" ${t}>
                    <h3>${recipes[n].name}</h3>
                    <p>${recipes[n].description}</p>
                    <p id="ingredients">Ingredients: ${recipes[n].ingredients.join(", ")}</p>
                `;i.innerHTML=a,e.appendChild(i)}}),document.addEventListener("DOMContentLoaded",function(){var e=document.getElementById("recipe-container");document.querySelectorAll("#recipe-nav a").forEach(function(n){n.addEventListener("click",function(n){n.preventDefault(),e.innerHTML="";var t=this.textContent.toLowerCase();recipes.forEach(function(n,i){if(n.typeof===t||"all"===t){var a=document.createElement("div");a.classList.add("recipe");var r=`
                                <img src="${recipes[i].image}" alt="${recipes[i].name}" width="300" height="300" loading="lazy">
                                <h3>${recipes[i].name}</h3>
                                <p>${recipes[i].description}</p>
                                <p id="ingredients">Ingredients: ${recipes[i].ingredients.join(", ")}</p>
                            `;a.innerHTML=r,e.appendChild(a)}})})})}),updateRandomRecipe();var name=localStorage.getItem("name");name&&"null"!==name?document.getElementById("greeting").textContent="Welcome back, "+name+"!":(name=prompt("What's your name?"),localStorage.setItem("name",name),document.getElementById("greeting").textContent="Welcome, "+name+"!");